services:

  mariadb:
    image: mariadb:10.11
    env_file:
      - server/.env.local
    environment:
      MYSQL_DATABASE: ${LOCAL_DB_NAME:-annonces}
      MYSQL_USER: ${LOCAL_DB_USER:-user}
      MYSQL_PASSWORD: ${LOCAL_DB_USER_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mariadb/data
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p${LOCAL_DB_ROOT_PASSWORD:-rootpassword}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # The apache service that install everything to run the symfony application and build the angular frontend
  webserver:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - server/.env.local
    environment:
      MYSQL_DATABASE: ${LOCAL_DB_NAME:-annonces}
      MYSQL_USER: ${LOCAL_DB_USER:-user}
      MYSQL_PASSWORD: ${LOCAL_DB_USER_PASSWORD:-password}
    ports:
      - "8080:80"
    depends_on:
      mariadb:
        condition: service_healthy

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app:delegated
      - node_modules_dev:/app/node_modules
    ports:
      - "4200:4200"

  # Tu pourrais me générer un dockerfile.dev pour le dev 
  webserver-dev:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    ports:
      - "8080:80"
    env_file:
      - server/.env.local
    environment:
      MYSQL_DATABASE: ${LOCAL_DB_NAME:-annonces}
      MYSQL_USER: ${LOCAL_DB_USER:-user}
      MYSQL_PASSWORD: ${LOCAL_DB_USER_PASSWORD:-password}
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./api:/var/www/api:delegated
      - vendor-dev:/var/www/api/vendor

volumes:
  mariadb:
  vendor-dev:
  node_modules_dev:
