services:
  backend-dev:
    build:
      context: backend/
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      AWS_ACCESS_KEY_ID: copy_key_here
      AWS_SECRET_ACCESS_KEY: copy_secret_here
      STRIPE_SECRET_KEY: sk_secret
      STRIPE_WEBHOOK_SECRET: whsec_secret
      AWS_DEFAULT_REGION: eu-north-1
      AWS_BUCKET_NAME: ebey-backend-files
      AWS_S3_CUSTOM_DOMAIN: dwnazphq75jed.cloudfront.net
      DB_HOST: postgres
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
            - "*.pyo"
            - "*.pyd"
            - .pytest_cache/
            - .coverage
            - htmlcov/
            - "*.egg-info/"

  backend-prod:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  angular-dev:
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - API_URL=http://localhost:8000/api/
      - STRIPE_PUBLISHABLE_KEY=pk_test_51S6S0NRuasokNTVWHlHwo3Pz8nkSNeqNmuGo0BoV2A3XE1iHMDK6UmCLRyLUMfblZxMvdqLGg2s9eAn7EoQF8abt00p7A4FSVR
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
          ignore:
            - node_modules/

#  angular-test:
#    build:
#      context: frontend/
#      dockerfile: Dockerfile.dev
#    ports:
#      - "9876:9876"
#    command: ["npm", "run", "test"]

volumes:
  pgdata:
