FROM python:3.13-slim

LABEL authors="uranus"

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc=4:14.2.0-1 \
        curl=8.14.1-2 \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir uv==0.8.8

# Copy dependency files
COPY pyproject.toml uv.lock ./

# Install Python dependencies
RUN uv sync --frozen

# Copy project
COPY . .

# Expose port
EXPOSE 8000

RUN chmod +x ./entrypoint.sh

# Run Django development server with hot reload
CMD ["./entrypoint.sh"]
