# Generated by Django 5.2.6 on 2025-09-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("clothes", "Vêtements"),
                    ("books", "Livres"),
                    ("cars", "Voitures"),
                    ("video_games", "Jeux-vidéos"),
                    ("sport", "Sport"),
                    ("home", "Maison"),
                    ("appliances", "Électroménager"),
                ],
                default="maison",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "Neuf"),
                    ("like_new", "Presque neuf"),
                    ("good", "Bon"),
                    ("acceptable", "Acceptable"),
                ],
                default="bon",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_mode",
            field=models.CharField(
                choices=[("hand_to_hand", "Main propre"), ("by_mail", "Poste")],
                default="poste",
                max_length=20,
            ),
        ),
    ]
