# Generated by Django 5.2.6 on 2025-09-16 09:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_category_alter_product_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("clothes", "Vêtements"),
                    ("books", "Livres"),
                    ("cars", "Voitures"),
                    ("video_games", "Jeux-vidéos"),
                    ("sport", "Sport"),
                    ("home", "Maison"),
                    ("appliances", "Électroménager"),
                ],
                default="home",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "Neuf"),
                    ("like_new", "Presque neuf"),
                    ("good", "Bon"),
                    ("acceptable", "Acceptable"),
                ],
                default="good",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_mode",
            field=models.CharField(
                choices=[("hand_to_hand", "Main propre"), ("by_mail", "Poste")],
                default="by_mail",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=None,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
