FROM php:8.2-apache

WORKDIR /var/www

RUN a2enmod rewrite

RUN apt-get update \
  && apt-get install -y libzip-dev git wget unzip --no-install-recommends \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN docker-php-ext-install pdo mysqli pdo_mysql zip

RUN wget https://getcomposer.org/download/2.8.3/composer.phar \
    && mv composer.phar /usr/bin/composer && chmod +x /usr/bin/composer

COPY api/ /var/www/api

ENV COMPOSER_ALLOW_SUPERUSER=1
RUN composer install -d /var/www/api

COPY server/apache.conf /etc/apache2/sites-enabled/000-default.conf

EXPOSE 80

CMD ["apache2-foreground"]
