# Generated by Django 5.2.6 on 2025-09-15 13:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_shipping_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="seller_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="seller_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CART", "Cart"),
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("SHIPPED", "Shipped"),
                    ("CANCELED", "Canceled"),
                    ("COMPLETED", "Completed"),
                ],
                default="CART",
                max_length=10,
            ),
        ),
    ]
