# Generated by Django 5.2.6 on 2025-09-17 12:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_orderitem_product_shipping_fee_orderitem_seller_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_category",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_shipping_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
